list all branches, fetch and merge with master

diff --git a/github-automerge-script b/github-automerge-script
--- a/github-automerge-script
+++ b/github-automerge-script
@@ -1,4 +1,5 @@
-#!/bin/bash -e
+#!/bin/bash
+set -e # exit with nonzero exit code if anything fails
 
 # clear and re-create the out directory
 rm -rf out || exit 0;
@@ -17,6 +18,9 @@ git config user.email "jovan1ivanovski@gmail.com"
 # will be lost, since we are overwriting it.) We redirect any output to
 # /dev/null to hide any sensitive credential data that might otherwise be exposed.
 git fetch --all
+
+git show-branch -all
+
 #git checkout master
 git merge --ff-only origin/development
 git push --force "https://${GH_TOKEN}@${GH_REF}" master > /dev/null 2>&1
